---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: triggertemplate-git-trigger
spec:
  params:
    - name: git-access-token
      description: the token to access the git repository for the clone operations
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: triggerName
      default: "git-pr-process"
    - name: pipeline-debug
      default: "false"

  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: $(params.triggerName)-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
          
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(params.triggerName)-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        params:
          - name: git-access-token
            value: $(params.git-access-token)
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: terraform_version
            value: $(params.terraform_version)
          - name: golang_version
            value: $(params.golang_version)
          - name: ansible_version
            value: $(params.ansible_version)
          - name: ansible_core_version
            value: $(params.ansible_core_version)
          - name: terraform_provisioner_version
            value: $(params.terraform_provisioner_version)
          - name: python_version
            value: $(params.python_version)
          - name: ibmcloud_api_key
            value: $(params.ibmcloud_api_key)
          - name: bastion_ssh_keys
            value: $(params.bastion_ssh_keys)
          - name: compute_ssh_keys
            value: $(params.compute_ssh_keys)
          - name: login_ssh_keys
            value: $(params.login_ssh_keys)
          - name: storage_ssh_keys
            value: $(params.storage_ssh_keys)
          - name: zones
            value: $(params.zones)
          - name: prefix
            value: $(params.prefix)
          - name: resource_group
            value: $(params.resource_group)
          - name: allowed_cidr
            value: $(params.allowed_cidr)
          - name: enable_cos_integration
            value: $(params.enable_cos_integration)
          - name: enable_atracker
            value: $(params.enable_atracker)
          - name: enable_vpc_flow_logs
            value: $(params.enable_vpc_flow_logs)
          - name: key_management
            value: $(params.key_management)
        workspaces:
          - name: shared-data
            persistentVolumeClaim:
              claimName: $(params.triggerName)-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-manual
spec:
  params:
    - name: repository
      value: $(params.repositoryForManualTrigger)
    - name: branch
      value: $(params.branch)
    - name: triggerName
      value: manual-trigger
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-manual
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-manual
      template:
        name: triggertemplate-git-trigger
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-github-pr
spec:
  params:
    - name: branch
      value: $(event.pull_request.base.ref)
    - name: target-branch
      value: $(event.pull_request.base.ref)
    - name: commit-id
      value: $(event.pull_request.head.sha)
    - name: commit-timestamp
      value: $(event.pull_request.head.repo.pushed_at)
    - name: target-commit-id
      value: $(event.pull_request.base.sha)
    - name: pr-url
      value: $(event.pull_request.url)
    - name: pr-number
      value: $(event.pull_request.number)
    - name: pr-name
      value: $(event.pull_request.user.login)
    - name: repository
      value: $(event.repository.html_url)
    - name: pr-repository
      value: $(event.pull_request.head.repo.html_url)
    - name: pr-branch
      value: $(event.pull_request.head.ref)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-github-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.url)"
    - name: revision
      value: "$(event.head_commit.id)"
    - name: branch
      value: "$(event.ref)"
    - name: triggerName
      value: "github-commit"
    - name: ibmcloud_api_key
      value: "$(event.ref)"
    - name: bastion_ssh_keys
      value: "$(event.ref)"
    - name: compute_ssh_keys
      value: "$(event.ref)"
    - name: login_ssh_keys
      value: "$(event.ref)"
    - name: storage_ssh_keys
      value: "$(event.ref)"
    - name: zones
      value: "$(event.ref)"
    - name: prefix
      value: "$(event.ref)"
    - name: resource_group
      value: "$(event.ref)"
    - name: allowed_cidr
      value: "$(event.ref)"
    - name: enable_cos_integration
      value: "$(event.ref)"
    - name: enable_atracker
      value: "$(event.ref)"
    - name: enable_vpc_flow_logs
      value: "$(event.ref)"
    - name: key_management
      value: "$(event.ref)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-github-pr
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-github-pr
      template:
        name: triggertemplate-git-trigger
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-github-commit
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-github-commit
      template:
        name: triggertemplate-git-trigger



